name: Release Please
on:
  workflow_call:
    inputs:
      app-id:
        description: 'The GitHub App ID'
        required: true
        type: string
      environment:
        description: 'The environment where to run workflow'
        required: false
        type: string
    secrets:
      app-private-key:
        description: 'The GitHub App private key'
        required: true

jobs:
  release-please:
    environment: ${{ inputs.environment || null }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ inputs.app-id }}
          private-key: ${{ secrets.app-private-key }}

      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
